@baseUrl = https://microbit-backend.velozz.workers.dev
@email = admin@velozz.com
@password = XDman100#
@authToken = {{login.response.body.$.sessionToken}}
@apiKey = velozz_admin_seed

### Health
GET {{baseUrl}}/v1/health

### Login
# @name login
POST {{baseUrl}}/v1/auth/login
content-type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Me
GET {{baseUrl}}/v1/auth/me
Authorization: Bearer {{authToken}}

### Seeded Admin Key
GET {{baseUrl}}/v1/admin/api-keys/{{apiKey}}
Authorization: Bearer {{authToken}}

### List API Keys
GET {{baseUrl}}/v1/admin/api-keys
Authorization: Bearer {{authToken}}

### Device Pull
GET {{baseUrl}}/v1/microbit/pull?deviceId={{apiKey}}

### Logout
POST {{baseUrl}}/v1/auth/logout
Authorization: Bearer {{authToken}}
